---
- hosts: kubeedge_cloud
  remote_user: root
  tasks:
    - name: unarchive keadm
      unarchive:
        src: /root/keadm-v1.5.0-linux-amd64.tar.gz
        dest: /root/keadm-v1.5.0-linux-amd64
    - name: copy keadm
      copy:
        src: /root/keadm-v1.5.0-linux-amd64/keadm/keadm
        dest: /usr/bin/keadm
        mode: 0755
        remote_src: yes
    - name: delete kubeedge directory
      file:
        path: /etc/kubeedge/
        state: absent
    - name: clear kubeedge binary
      file:
        path: /root/kubeedge/
        state: absent
    - name: turn off swap
      command: swapoff -a
    - name: kubeadm reset
      expect:
        command: kubeadm reset
        responses:
          "Are you sure you want to proceed?": "y"
      register: result
    - name: kubeadm init
      command: kubeadm init --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers
    - name: remove .kube directory
      file:
        path: /root/.kube/
        state: absent
    - name: create .kube directory
      file:
        path: /root/.kube/
        state: directory
    - name: copy .kube file
      command: cp /etc/kubernetes/admin.conf /root/.kube/config
    - name: fetch .kube file
      fetch:
        src: /root/.kube/config
        dest: /root/ansible_kubeedge/.kube/config
        flat: yes
    - name: remove daemonset kube-proxy
      command: kubectl delete daemonset -n kube-system kube-proxy
      ignore_errors: True
    - name: remove deploy kube-dns
      command: kubectl delete deploy -n kube-system coredns
      ignore_errors: True
    - name: remove endpoint kube-dns
      command: kubectl delete endpoint -n kube-system kube-dns
      ignore_errors: True
#    - debug: var=hostvars['cloud_server']['ansible_ssh_host']
    - name: keadm init
      command: keadm init --advertise-address={{hostvars['cloud_server']['ansible_ssh_host']}} --kube-config=/root/.kube/config