---
- hosts: kubeedge_cloud
  remote_user: root
  tasks:
    - name: delete kubeedge directory
      file:
        path: /etc/kubeedge/
        state: absent
    - name: clear kubeedge binary
      file:
        path: /root/kubeedge/
        state: absent
    - name: copy kubeedge binary
      copy:
        src: /root/ansible_kubeedge/kubeedge/
        dest: /root/kubeedge/
        owner: root
    - name: turn off swap
      command: swapoff -a
    - name: kubeadm reset
      expect:
        command: kubeadm reset
        responses:
          "Are you sure you want to proceed?": "y"
      register: result
#    - debug: var=result
    - name: kill cloudcore
      command: killall cloudcore
      ignore_errors: yes
    - name: kubeadm init
      command: kubeadm init --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers
    - name: remove .kube directory
      file:
        path: /root/.kube/
        state: absent
    - name: create .kube directory
      file:
        path: /root/.kube/
        state: directory
    - name: copy .kube file
      command: cp /etc/kubernetes/admin.conf /root/.kube/config
#      copy: src=/etc/kubernetes/admin.conf dest=/root/.kube/config
#      copy:
#        src: /etc/kubernetes/admin.conf
#        dest: /root/.kube/config
    - name: fetch .kube file
      fetch:
        src: /root/.kube/config
        dest: /root/ansible_kubeedge/.kube/config
        flat: yes
    - name: remove kube-proxy
      command: kubectl delete daemonset -n kube-system kube-proxy
      ignore_errors: True
    - name: remove kube-dns
      command: kubectl delete deploy -n kube-system coredns
      ignore_errors: True
    - name: create kubeedge directory
      file:
        path: /etc/kubeedge/config/
        state: directory
    - name: chmod +x cloudcore binary
      file:
        path: /root/kubeedge/cloud/cloudcore/cloudcore
        mode: 0755
    - name: create cloudcore.yaml
      shell: /root/kubeedge/cloud/cloudcore/cloudcore --defaultconfig > /etc/kubeedge/config/cloudcore.yaml
    - name: create kubeedge device
      command: kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha2_device.yaml
    - name: create kubeedge devicemodel
      command: kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/devices/devices_v1alpha2_devicemodel.yaml
    - name: create kubeedge cluster_objectsync
      command: kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/reliablesyncs/cluster_objectsync_v1alpha1.yaml
    - name: create kubeedge objectsync
      command: kubectl apply -f https://raw.githubusercontent.com/kubeedge/kubeedge/master/build/crds/reliablesyncs/objectsync_v1alpha1.yaml
    - name: copy cloudcore.service
      copy:
        src: /root/ansible_kubeedge/cloudcore.service
        dest: /etc/systemd/system/cloudcore.service
    - name: enable cloudcore.service
      command: systemctl enable cloudcore.service
    - name: restart cloudcore.service
      command: systemctl restart cloudcore.service
- hosts: kubeedge_edge
  remote_user: root
  tasks:
    - name: kubeadm reset
      expect:
        command: kubeadm reset
        responses:
          "Are you sure you want to proceed?": "y"
      register: result
    - name: delete kubeedge directory
      file:
        path: /etc/kubeedge/
        state: absent
    - name: clear kubeedge binary
      file:
        path: /root/kubeedge/
        state: absent
    - name: copy kubeedge binary
      copy:
        src: /root/ansible_kubeedge/kubeedge/
        dest: /root/kubeedge/
        owner: root
    - name: remove .kube directory
      file:
        path: /root/.kube/
        state: absent
    - name: create .kube directory
      file:
        path: /root/.kube/
        state: directory
    - name: copy .kube file
      copy:
        src: /root/ansible_kubeedge/.kube/config
        dest: /root/.kube/config
    - name: turn off swap
      command: swapoff -a
    - name: kill edgecore
      command: killall edgecore
      ignore_errors: yes
    - name: create kubeedge directory
      file:
        path: /etc/kubeedge/config/
        state: directory
    - name: chmod +x cloudcore binary
      file:
        path: /root/kubeedge/edge/edgecore
        mode: 0755
    - name: create edgecore.yaml
      shell: /root/kubeedge/edge/edgecore --defaultconfig > /etc/kubeedge/config/edgecore.yaml
    - name: change cgroups driver
      replace:
        path: /etc/kubeedge/config/edgecore.yaml
        regexp: cgroupfs
        replace: systemd
    - name: get token
      shell: kubectl get secret -nkubeedge tokensecret -o=jsonpath='{.data.tokendata}' | base64 -d
      register: result
    #    - debug: var=result
    - name: set token
      replace:
        path: /etc/kubeedge/config/edgecore.yaml
        regexp: 'token: ""'
        replace: 'token: "{{result.stdout}}"'
    - name: set server ip
      replace:
        path: /etc/kubeedge/config/edgecore.yaml
        regexp: 'token: ""'
        replace: 'token: "{{hostvars[''cloud_server''][''ansible_ssh_host'']}}"'
    - name: stop kubelet
      command: systemctl stop kubelet
    - name: copy edgecore.service
      copy:
        src: /root/ansible_kubeedge/edgecore.service
        dest: /etc/systemd/system/edgecore.service
    - name: enable edgecore.service
      command: systemctl enable edgecore.service
    - name: restart cloudcore.service
      command: systemctl restart edgecore.service
#    - debug: var=hostvars['cloud_server']['ansible_ssh_host']
    - name: edit modules.edgeHub.httpServer
      command: yq w -i /etc/kubeedge/config/edgecore.yaml modules.edgeHub.httpServer https://{{hostvars['cloud_server']['ansible_ssh_host']}}:10002
    - name: edit modules.edgeHub.quic.server
      command: yq w -i /etc/kubeedge/config/edgecore.yaml modules.edgeHub.quic.server {{hostvars['cloud_server']['ansible_ssh_host']}}:10001
    - name: edit modules.edgeHub.websocket.server
      command: yq w -i /etc/kubeedge/config/edgecore.yaml modules.edgeHub.websocket.server {{hostvars['cloud_server']['ansible_ssh_host']}}:10000
    - name: copy edgecore.service
      copy:
        src: /root/ansible_kubeedge/edgecore.service
        dest: /etc/systemd/system/edgecore.service
    - name: enable edgecore.service
      command: systemctl enable edgecore.service
    - name: restart edgecore.service
      command: systemctl restart edgecore.service